name: "Hardwario BCG"
version: 7
slug: "hardwario_bcg"
description: "Addon for Hardwario USB radio dongle!"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
devices: 
  - "/dev/ttyUSB0"
options:
  mqtt_host: "localhost"
  mqtt_host_port: 1883
  mqtt_username: "username"
  mqtt_password: "password"
  usb_port: "/dev/ttyUSB0" 
  debug: false
schema:
  mqtt_host: str
  mqtt_host_port: int
  mqtt_username: str
  mqtt_password: str
  usb_port: str
  debug: bool

